# CI workflow used for code quality checks and to ensure that a PR can be built.
# Future tests might also be executed by this workflow.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    lint:
        name: Run eslint and test and build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v3
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

            - uses: actions/setup-node@v2
              with:
                  node-version: 16.x
            - run: yarn
            - run: yarn package
            - run: yarn lint

            - name: Attach KIELER VS Code Extension (no server)
              uses: actions/upload-artifact@v4
              with:
                  name: KIELER VS Code Extension (no server)
                  path: keith-vscode/keith-vscode.vsix
                  if-no-files-found: error
